# Generated by Django 5.2.4 on 2025-07-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='moodle_user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
