# Generated by Django 5.2.4 on 2025-07-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='scfhs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
