# Generated by Django 5.2.4 on 2025-07-31 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('cme_credits', models.DecimalField(decimal_places=1, max_digits=4)),
                ('price_before', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_after', models.DecimalField(decimal_places=2, max_digits=8)),
                ('thumbnail', models.ImageField(upload_to='course_thumbnails/')),
                ('course_id', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, to='course.category')),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'manager', 'teacher']}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
