# Generated by Django 5.2.4 on 2025-07-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
