# Generated by Django 5.2.4 on 2025-07-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
